
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Option extends javax.swing.JFrame {

    /**
     * Creates new form Option
     */
    public Option() {
        initComponents();
        maxi();
        display1();
        clear();
    }
    void clear(){
        s2.setText("");
        s3.setDate(null);
        s4.setDate(null);
      
    }
 public void maxi()
    {
       try{
            
            Class.forName("com.mysql.jdbc.Driver");

            Connection z1=DriverManager.getConnection( "jdbc:mysql://localhost:3306/college?","root","");
            
            int count=1;
           Statement sp1=z1.createStatement();
            ResultSet rs3=sp1.executeQuery("select * from student");
            
            while(rs3.next())
            {
                count = rs3.getInt("student_no");
            }
            count = count +1;
            String no =String.valueOf(count);
           s1.setText(no);
             
         
        }catch(Exception e){System.out.println(e);}  
    }
      public void display1()
    {
              try{
            
            Class.forName("com.mysql.jdbc.Driver");

            Connection z1=DriverManager.getConnection( "jdbc:mysql://localhost:3306/college?","root","");
            // System.out.println("Connecton Successful");
             String sq1="select * from student";
             PreparedStatement ps= z1.prepareStatement(sq1);
             ResultSet rs=ps.executeQuery();
             o1.setModel(DbUtils.resultSetToTableModel(rs));
             
             
         
        }catch(Exception e){System.out.println(e);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        s3 = new com.toedter.calendar.JDateChooser();
        s4 = new com.toedter.calendar.JDateChooser();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton27 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        o1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel1.setText("Student Records");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Student  Roll No   :");

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("Student  Name      :");

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Student   DOB       :");

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("Student   DOJ        :");

        s1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        s1.setToolTipText("Student Roll Number...");
        s1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                s1KeyPressed(evt);
            }
        });

        s2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        s2.setToolTipText("Enter Student Name 1...");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        s2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                s2KeyPressed(evt);
            }
        });

        s3.setToolTipText("Enter DOB Date");

        s4.setToolTipText("enter DOJ Date");

        jButton14.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton14.setText("Add New");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton13.setText("Update");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton15.setText("Delete");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(204, 204, 0));

        jLabel26.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Search Student Name No :");

        search.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        search.setToolTipText("Enter Name...");
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        jButton27.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton27.setText("Go");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Display All Record's :");

        jButton28.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton28.setText("Go");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel26)
                .addGap(40, 40, 40)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton27)
                .addGap(70, 70, 70)
                .addComponent(jLabel27)
                .addGap(40, 40, 40)
                .addComponent(jButton28)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27)
                    .addComponent(jLabel27)
                    .addComponent(jButton28))
                .addContainerGap())
        );

        o1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        o1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(o1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(s2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(s1)))
                    .addComponent(s4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(989, 989, 989))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15)
                            .addComponent(jButton13)
                            .addComponent(jButton14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_s1KeyPressed

    }//GEN-LAST:event_s1KeyPressed

    private void s2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_s2KeyPressed

    }//GEN-LAST:event_s2KeyPressed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
try{
            //String a=jTextField1.getText();

            int id=Integer.valueOf(s1.getText());
            String name=s2.getText().toString();
            
                     
            Date date1=s3.getDate();
            String dob=DateFormat.getDateInstance().format(date1).toString();  
            Date date11=s4.getDate();
            String doj=DateFormat.getDateInstance().format(date11).toString();    
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection z1=DriverManager.getConnection( "jdbc:mysql://localhost:3306/college?","root","");
            
            PreparedStatement ps2= z1.prepareStatement("insert into student values(?,?,?,?)");
            ps2.setInt(1, id);
            ps2.setString(2, name);
            ps2.setString(3, dob);
            ps2.setString(4, doj);
            ps2.execute();

           
            //c1.commit();
            z1.close();
            display1();
           
           JOptionPane.showMessageDialog(this,""+name+" Record Add Successfuly","Save Recod's",JOptionPane.INFORMATION_MESSAGE);
            maxi();
             clear();
             }
          
        catch(Exception  e)
        {
            JOptionPane.showMessageDialog(this,e,"ALLERT MESSAGE",JOptionPane.WARNING_MESSAGE);
        }       
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
           try{

            int id=Integer.valueOf(s1.getText());
            String name=s2.getText().toString();
            
                     
            Date date1=s3.getDate();
            String dob=DateFormat.getDateInstance().format(date1).toString();  
            Date date11=s4.getDate();
            String doj=DateFormat.getDateInstance().format(date11).toString();
            
            
            Class.forName("com.mysql.jdbc.Driver");

            Connection c1=DriverManager.getConnection( "jdbc:mysql://localhost:3306/college?","root","");
            // System.out.println("Connecton Successful");

            PreparedStatement ps1= c1.prepareStatement("Update student set STUDENT_NAME=?, STUDENT_DOB=?, STUDENT_DOj=? where STUDENT_NO=?");
            ps1.setString(1, name);
             ps1.setString(2, dob);
            ps1.setString(3, doj);
            ps1.setInt(4, id);
            ps1.executeUpdate();

           
            //c1.commit();
            c1.close();
            display1();
            JOptionPane.showMessageDialog(this,""+id+" Record Update Successfuly","Update Record's",JOptionPane.INFORMATION_MESSAGE);
             clear();
             }           
        
        catch(Exception  e)
        {
            JOptionPane.showMessageDialog(this,e,"ALLERT MESSAGE",JOptionPane.WARNING_MESSAGE);
        }       
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try{

        
              int id=Integer.valueOf(s1.getText());
            Class.forName("com.mysql.jdbc.Driver");

            Connection z1=DriverManager.getConnection( "jdbc:mysql://localhost:3306/college?","root","");
            // System.out.println("Connecton Successful");

            PreparedStatement ps1= z1.prepareStatement("Delete from student where student_no=?");
            ps1.setInt(1, id);
            ps1.executeUpdate();

           
            z1.close();
            display1();
         
             JOptionPane.showMessageDialog(this,""+id+" Record Delete Successfuly","Delete Record's",JOptionPane.INFORMATION_MESSAGE);
                maxi();
             clear();
        }
        catch(Exception  e)
        {
            JOptionPane.showMessageDialog(this,e,"ALLERT MESSAGE",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed

    }//GEN-LAST:event_searchKeyPressed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
       try{
            //String a=jTextField1.getText();
            String name =search.getText().toString();
            //String name = jComboBox1.getSelectedItem().toString();

            Class.forName("com.mysql.jdbc.Driver");

           Connection z1=DriverManager.getConnection( "jdbc:mysql://localhost:3306/college?","root","");
            // System.out.println("Connecton Successful");

            PreparedStatement ps1= z1.prepareStatement("select * from student where Student_name=?");
            ps1.setString(1, name);

           
            ResultSet rs=ps1.executeQuery();

            // p1.setModel(DbUtils.resultSetToTableModel(rs));
          
            //  p1.setModel(DbUtils.resultSetToTableModel(rs));
            
            PreparedStatement ps2= z1.prepareStatement("select * from student where student_name=?");
            ps2.setString(1,name);
            ResultSet rs1=ps1.executeQuery();
            o1.setModel(DbUtils.resultSetToTableModel(rs1));

            z1.close();
            JOptionPane.showMessageDialog(this,""+name+" Conductor Search Successfuly","Search Record's",JOptionPane.INFORMATION_MESSAGE);
            search.setText("");
        }
        catch(Exception  e)
        {
            JOptionPane.showMessageDialog(this,e,"ALLERT MESSAGE",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
           display1();
    }//GEN-LAST:event_jButton28ActionPerformed

    private void o1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o1MouseClicked
       
    }//GEN-LAST:event_o1MouseClicked

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable o1;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private com.toedter.calendar.JDateChooser s3;
    private com.toedter.calendar.JDateChooser s4;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
